language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.* TS_SPREADSHEET_ID="1lMZxVs7a5A8Xy4Z-15d3znE0NpOwnXQItReGPa7W8bw"
      php: 7.2
    - env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.* TS_SPREADSHEET_ID="1rqvOz7l07T2ouX0g0uHLEC2s4DfLrsDFtIfRSjES98g"
      php: 7.3

before_install:
    - test $TRAVIS_PULL_REQUEST == "false" && openssl aes-256-cbc -K $encrypted_5affb966e7f5_key -iv $encrypted_5affb966e7f5_iv -in tests/fixtures/service-account.json.enc -out tests/fixtures/service-account.json -d
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update -v
    - composer require "illuminate/console:${ILLUMINATE_VERSION}" --no-update -v
    - composer require "illuminate/filesystem:${ILLUMINATE_VERSION}" --no-update -v
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --dev --no-update -v

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
